name: Deploy Dev - Netlify

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout da branch dev
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Deploy na Netlify
        uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: '.'
          production-deploy: true
          deploy-message: "Deploy manual da branch dev"
          enable-pull-request-comment: false
          enable-commit-comment: false
          overwrites-pull-request-comment: false

        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN_DEV }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_DEV }}
